apiVersion: v1
kind: Service
metadata:
  name: paf-admin-mysql
  labels:
    app: paf-admin
spec:
  ports:
    - port: 3306
  selector:
    app: paf-admin
    tier: mysql
  clusterIP: None
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  labels:
    app: paf-admin
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: paf-admin-mysql
  labels:
    app: paf-admin
spec:
  selector:
    matchLabels:
      app: paf-admin
      tier: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: paf-admin
        tier: mysql
    spec:
      containers:
      - image: ${IMAGE}
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: ${MYSQL_ROOT_PASSWORD}
        - name: MYSQL_DATABASE
          value: paf-admin
        - name: MYSQL_USER
          value: paf-admin
        - name: MYSQL_PASSWORD
          value: ${MYSQL_PASSWORD}
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim
