apiVersion: v1
kind: Service
metadata:
  name: paf-admin-mysql
  labels:
    app: paf-admin
spec:
  ports:
    - port: 3306
  selector:
    app: paf-admin
    tier: mysql
  clusterIP: None
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  labels:
    app: paf-admin
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: paf-admin-mysql
  labels:
    app: paf-admin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: paf-admin
      tier: mysql
  template:
    metadata:
      labels:
        app: paf-admin
        tier: mysql
    spec:
      containers:
      - name: mysql
        image: ${IMAGE}
#      - image: paf-admin-mysql
#        imagePullPolicy: Never
        resources:
          requests:
            memory: 2Gi
        env:
          - name: MYSQL_DATABASE
            valueFrom:
              configMapKeyRef:
                name: paf-admin-mysql
                key: mysql_database
          - name: MYSQL_PASSWORD
            valueFrom:
              configMapKeyRef:
                name: paf-admin-mysql
                key: mysql_password
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              configMapKeyRef:
                name: paf-admin-mysql
                key: mysql_root_password
          - name: MYSQL_USER
            valueFrom:
              configMapKeyRef:
                name: paf-admin-mysql
                key: mysql_user
        livenessProbe:
          tcpSocket:
            port: 3306
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim
