name: DEV - Docker Build, Upload and Kubernetes Deploy

on: workflow_dispatch

env:
  # Set global action env variables for DEV:
  IMAGE_TAG: paf-admin-mysql-dev
  KUBE_NAMESPACE: dev

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push container image to GitHub Container Registry
        id: build
        run: |
          IMAGE="ghcr.io/paf-it/${{ env.IMAGE_TAG }}:${{ github.sha }}"
          echo "image=$IMAGE" >> "$GITHUB_OUTPUT"
          docker build . --tag ${{ env.IMAGE_TAG }}
          docker tag ${{ env.IMAGE_TAG }} $IMAGE
          docker push $IMAGE

      - name: Set kubectl Context
        uses: azure/k8s-set-context@v4
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.UPCLOUD_KUBECONFIG }}
          context: ${{ env.KUBE_NAMESPACE }}

      - name: Deploy to Kubernetes
        uses: swdotcom/update-and-apply-kubernetes-configs@v1
        with:
          k8-config-file-paths: |
            k8s/mysql-configmap.yaml
            k8s/mysql-pvc.yaml
            k8s/mysql-service.yaml
            k8s/mysql-deployment.yaml
          replacement-method: defined
          namespace: ${{ env.KUBE_NAMESPACE }}
        env:
          IMAGE: ${{ steps.build.outputs.image }}
          MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}
          MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
          MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
          MYSQL_USER: ${{ secrets.MYSQL_USER }}
