name: Docker Build and Upload

on: workflow_dispatch

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push container image to GitHub Container Registry
        run: |
          docker build . --tag paf-admin-mysql
           tags="${{ github.ref_name }} ${{ github.sha }}"
            for tag in $tags; do
            docker tag paf-admin-mysql ghcr.io/paf-it/paf-admin-mysql:$tag
            docker push ghcr.io/paf-it/paf-admin-mysql:$tag
          done

      # Insert here: UpCloud Kubernetes credentials

      - name: Set Kubernetes deployment image
        uses: swdotcom/update-and-apply-kubernetes-configs@v1
        with:
          k8-config-file-paths: |
            k8/mysql-configmap.yaml
            k8/mysql-deployment.yaml
          replacement-method: defined
        env:
          IMAGE: ghcr.io/paf-it/paf-admin-mysql:$tag
          MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}
          MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
          MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
          MYSQL_USER: ${{ secrets.MYSQL_USER }}