name: Docker Build and Upload

on: workflow_dispatch

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push container image to GitHub Container Registry
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
          MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
        run: |
          docker build . --tag docker-playground-mysql
           tags="${{ github.ref_name }} ${{ github.sha }}"
            for tag in $tags; do
            docker tag docker-playground-mysql ghcr.io/paf-it/docker-playground-mysql:$tag
            docker push ghcr.io/paf-it/docker-playground-mysql:$tag
          done

      - name: Insert cr value and secrets into kubernetes manifest
        uses: swdotcom/update-and-apply-kubernetes-configs@v1
        with:
          k8-config-file-paths: k8/mysql-deployment.yaml
          replacement-method: defined
        env:
          IMAGE: ghcr.io/paf-it/docker-playground-mysql:$tag
          MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
          MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}