name: kubernetes_upcloud_test.yaml

on: workflow_dispatch

jobs:
  test-kubectl:
    name: kubectl Test
    runs-on: ubuntu-latest

    steps:
      - name: kubectl echo
        run: |
          # Generate kubeconfig using the kubeconfig from secrets instead
          echo "${{ secrets.UPCLOUD_KUBECONFIG }}" > prodxcloud-cluster-dev_kubeconfig.yaml
          
          # Verify kubeconfig was created
          if [ ! -f prodxcloud-cluster-dev_kubeconfig.yaml ]; then
            echo "Failed to generate kubeconfig"
            exit 1
          fi
          
          # Set KUBECONFIG environment variable
          export KUBECONFIG=$(pwd)/prodxcloud-cluster-dev_kubeconfig.yaml
          
          # Verify cluster access
          CLUSTER_INFO=$(kubectl cluster-info)
          echo "Cluster info: $CLUSTER_INFO"
          
          # Get the current context name
          CURRENT_CONTEXT=$(kubectl config current-context)
          echo "Current context: $CURRENT_CONTEXT"